# Generated by Django 4.1.5 on 2023-01-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_info',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
