# Generated by Django 4.1.5 on 2023-01-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altered_auth', '0003_alter_customuser_is_active_useremailrestorationdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremailrestorationdata',
            old_name='hidden_token',
            new_name='initial_string',
        ),
    ]
