# Generated by Django 4.1.5 on 2023-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altered_auth', '0004_rename_hidden_token_useremailrestorationdata_initial_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailrestorationdata',
            name='initial_string',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='useremailrestorationdata',
            name='text_token',
            field=models.CharField(max_length=36),
        ),
    ]
